/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all tasks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns all tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            title: string;
                            position: number;
                            tasks: {
                                id: number;
                                title: string;
                                position: string;
                                columnId: number;
                            }[];
                        }[];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Task data to create */
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "title": "Fix login bug",
                     *       "columnId": 1
                     *     }
                     */
                    "application/json": {
                        title: string;
                        columnId: number;
                    };
                };
            };
            responses: {
                /** @description Task created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 1,
                         *       "title": "Fix login bug",
                         *       "position": "0|10000:",
                         *       "columnId": 1
                         *     }
                         */
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                            errors: {
                                code: string;
                                message: string;
                                path?: (string | number)[];
                            }[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a task */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 1,
                         *       "title": "Fix login bug",
                         *       "position": "0|10000:",
                         *       "columnId": 1
                         *     }
                         */
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a task's fields (e.g. title) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            /** @description Fields to update */
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "title": "Updated title"
                     *     }
                     */
                    "application/json": {
                        title: string;
                    };
                };
            };
            responses: {
                /** @description Task updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 1,
                         *       "title": "Updated title",
                         *       "position": "0|10000:",
                         *       "columnId": 2
                         *     }
                         */
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                            errors: {
                                code: string;
                                message: string;
                                path?: (string | number)[];
                            }[];
                        };
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Move a task to another column and/or position
         * @description Recalculates the task's position based on the tasks it should end up between. Omit prevId/nextId when the task is dropped at the start/end of the column or into an empty column.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            /** @description Target column and surrounding tasks */
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "columnId": 2,
                     *       "prevId": 4,
                     *       "nextId": 7
                     *     }
                     */
                    "application/json": {
                        columnId: number;
                        prevId?: number | null;
                        nextId?: number | null;
                    };
                };
            };
            responses: {
                /** @description Task moved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 1,
                         *       "title": "Updated title",
                         *       "position": "0|10000:",
                         *       "columnId": 2
                         *     }
                         */
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                            errors: {
                                code: string;
                                message: string;
                                path?: (string | number)[];
                            }[];
                        };
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Task: {
            id: number;
            title: string;
            position: string;
            columnId: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
